version: "3.7"
services:
  webadmin:
    container_name: farmageosql-webadmin
    restart: always
    build:
      dockerfile: ./Dockerfile.prod
    image: farmageoadminsql:latest
    ports:
      - "3150:80"
