# build environment
FROM node:lts-alpine as build
WORKDIR /admin
ENV PATH /admin/node_modules/.bin:$PATH
COPY package.json ./

RUN npm install --legacy-peer-deps --silent

COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /admin/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]