## API MEMBERSHIO WP###
POST http://167.172.241.218:8000/wp-json/jwt-auth/v1/token
content-type: application/json

{
        "username": "admin",
        "password": "nosenose"
}

###
POST http://167.172.241.218:8000/wp-json/jwt-auth/v1/token
content-type: application/json

{
        "username": "prueba1",
        "password": "prueba1"
}

###
GET http://167.172.241.218:8000/wp-json/wp/v2/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xNjcuMTcyLjI0MS4yMTg6ODAwMCIsImlhdCI6MTU4OTU3OTU0NSwibmJmIjoxNTg5NTc5NTQ1LCJleHAiOjE1OTAxODQzNDUsImRhdGEiOnsidXNlciI6eyJpZCI6IjIifX19.y6Em294Rj1WvgZzVKgAYQqeVmIv7OzMSXI2x-AvgUWY

###API FARMAGEO
POST http://68.183.31.49:3000/productos/ HTTP/1.1
content-type: application/json

    {
        "imagen": "/assets/productos/termometro.png",
        "nombre": "Termometro Digital Citizen",
        "sku": "ZI423524",
        "inventario": "Hay existencias",
        "precio": "$250",
        "favorito": true,
        "fecha": "12/1/2020"
    } 

### WP-ADMIN API

###
POST http://167.172.241.218:8000/wp-json/jwt-auth/v1/token
content-type: application/json

{
        "username": "farmacia1",
        "password": "farmacia1"
}


### Crear usuario

POST http://167.172.241.218:8000/wp-json/wp/v2/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xNjcuMTcyLjI0MS4yMTg6ODAwMCIsImlhdCI6MTU5MDM2MDYwNSwibmJmIjoxNTkwMzYwNjA1LCJleHAiOjE1OTA5NjU0MDUsImRhdGEiOnsidXNlciI6eyJpZCI6IjIifX19.wm8yytaATu4_3LltISHa7R4aI7PzqSRug8Bg7baJ7kw
content-type: application/json

{
        "username": "qwerty@gmail.com",
        "password": "1234567",
        "name": "qwerty",
        "first_name": "user",
        "last_name": "qwerty",
        "email": "qwerty@gmail.com",
        "roles": [ "usuario" ]
}

##########
POST http://167.172.241.218:3110/users/token/validate
content-type: application/json

{
        "usuario": "admin",
        "password": "nosenose"
}


#######
POST http://167.172.241.218:3110/farmacias/admin/passwords
content-type: application/json

{
        "usuario": "admin",
        "password": "nosenose"
}

#######
POST http://167.172.241.218:3110/denuncias
content-type: application/json

{
        "motivo": "Envía imágenes inapropiadas",
        "username_denunciante": "F1577104",
        "username_denunciado": "miru@gmail.com",
        "nombre_denunciado": "miru@gmail.com",
        "tipodenuncia": "farmacia-usuario"
}

#######
//prueba para enviar emails
POST  http://167.172.241.218:3110/pedidos/email
content-type: application/json

{
        "destinatario": "psluortolani@gmail.com",
        "asunto": "mensaje",
        "html": "<b>Hola mi amor, Te amo!!</b>"
}
####### Prueba para enviar emails
POST  http://167.172.241.218:3110/pedidos
content-type: application/json

{
        "username": "lara@gmail.com", 
        "descripcion": "prueba",
        "comentarios": "prueba",    
        "estado": "nuevo",
        "idfarmacia": "6398",       
        "idsocio": "5e9efdf8027cdd00014c9547",  
        "envio": false,
        "costoenvio": 0,
        "pago_online": false,
        "gruposproductos": null,
        "domicilioenvio": "",
        "nombrefarmacia": "DONADO",
        "whatsapp": "3415703403",
        "destinatario": "santiagoalarcon2@hotmail.com",
        "asunto": "mensaje",
        "html": "<b>Esta es una confirmación de tu pedido</b>"
}

####### Enviar password por email #######
POST  http://167.172.241.218:3110/users/enviarpassword
content-type: application/json

{
        "username": "prueba2@gmail.com"
}

####### recuperar los password que faltan por email #######
POST  http://167.172.241.218:3110/users/passwordsfaltantes
content-type: application/json

{
        "username": "santiagoalarcon2@gmail.com",
        "password": "1234567"
}
